### ISSUE TITLE
QR code scanner in app

### ISSUE THREAD

**Issue by svub** [nimiq/gift-cards#9]
Many phones don't support QR code scanning w/t an app + many users don't know how to scan QR codes.
Thus, either we follow #7, or put a generic link on the each card, e.g. `nimiq.com/card/redeem` that then has a scanner that works for sure. 

I guess either this or #7 should be implemented.

Advantage of #7: it works for sure, even if the user's device doesn't have a camera
Downside of #7: Requires centralized service to shorten URL

**Comment by danimoh** [comment]
I now implemented this.
